from typing import Any, Callable, Dict, List, Optional, Set, Tuple, Type, Union, overload
import os

# 基本类型
class Context:
    """V8 JavaScript执行上下文"""
    def __init__(self, global_this: Any, hook: bool = False, ctx_type: Optional[str] = None, timeout: Optional[float] = None) -> None: ...
    def exec_js(self, script: str, filename: Optional[str] = None, timeout: Optional[float] = None) -> Any: ...
    def js_obj(self, py_object: Any) -> Optional[JSObject]: ...
    def expose(self, obj: Any, name: Optional[str] = None) -> Any: ...
    def expose_module(self, module: Any) -> Any: ...
    def gc(self) -> None: ...
    @property
    def glob(self) -> JSObject: ...
    @property
    def timeout(self) -> float: ...
    @timeout.setter
    def timeout(self, value: float) -> None: ...

    # 下面的方法实际上操作的是globalThis对象
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __getitem__(self, name: str) -> Any: ...
    def __setitem__(self, name: str, value: Any) -> None: ...

class Script:
    """V8 JavaScript脚本"""
    def __init__(self, context: Context, source: str, name: Optional[str] = None) -> None: ...

class Debugger:
    """V8 JavaScript调试器"""
    def __init__(self, context: Context) -> None: ...
    def send(self, message: str) -> None: ...

class JSObject:
    """JavaScript对象的Python封装"""
    def __dir__(self) -> List[str]: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __iter__(self) -> Any: ...
    def __eq__(self, other: JSObject) -> bool: ...
    def __repr__(self) -> str: ...

class JSFunction(JSObject):
    """JavaScript函数的Python封装"""
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __repr__(self) -> str: ...

class JSPromise(JSObject):
    """JavaScript Promise的Python封装"""
    def __init__(self, resolve: Optional[Any] = None, reject: Optional[Any] = None) -> None: ...
    def __repr__(self) -> str: ...

class JSTypeArray(JSObject):
    """JavaScript TypedArray的Python封装"""
    def __init__(self, data: List[Union[int, float]], typed: int) -> None: ...
    def __repr__(self) -> str: ...

class JSException(Exception):
    """JavaScript异常的Python封装"""
    pass

class JavaScriptTerminated(Exception):
    """JavaScript执行终止异常"""
    pass

# 单例对象
Null: JSObject
Undefined: JSObject

# 初始化v8
def init_v8(icudtl_path: Optional[str] = None, params: Optional[List[str]] = None) -> bool: ...

# 执行isolate->RequestGarbageCollectionForTesting();触发v8垃圾回收
def v8_gc() -> None: ...

# 获取当前v8 Context
def current_context() -> Optional[Context]: ...

# 从给定的构造函数创建一个新的JavaScript对象
def new(constructor: Any) -> Any: ...

# v8版本
def v8_version() -> str: ...
